const passwordReg = /^(?=.*[a-z])(?=.*\d)(?=.*[@$#!%*^?&])[A-Za-z\d@#$!%^*?&]{8,16}$/
const emailReg = /[a-zA-Z0-9.-_%+]+@[a-zA-Z0-9.-]+\.[a-z]{2,}$/;
const englishReg = /^[a-zA-Z]+/;
const englishNumberReg = /^[a-zA-Z0-9]+/;
const koreanhReg = /^[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]+/;
const numberReg = /^[0-9]+$/g;
const phoneNumberReg = /^01([0|1|6|7|8|9]{1})+([0-9]{3,4})?([0-9]{4})$/;
const phoneNumberDashReg = /^01([0|1|6|7|8|9]{1})-+([0-9]{3,4})-+([0-9]{4})$/;
const normalTelDashReg = /^([0-9]{2,3})-+([0-9]{3,4})-+([0-9]{4})$/;
const bussinessNumberReg = /^[0-9]{3}[-]+[0-9]{2}[-]+[0-9]{5}$/;
const specialReg = /^[\{\}\[\]\/?.,;:|\)*~`!^\-_+&lt;&gt;@\#$%&amp;\\\=\(\'\"]$/g;
